#------------------------------------------------------------------------------
# File:   Makefile
# Autores:  Razvan Ghita Calangiu 927460    Rodrigo Herce Alonso 935413
# Date:   mayo 2025
# Coms:   Makefile para compilar Trabajo GSenku   
#------------------------------------------------------------------------------

#---------------------------------------------------------
# Definición de macros
CC = g++
CPPFLAGS = -std=c++11
RM = rm -f

#---------------------------------------------------------
# Regla principal
all: mainGSenku

#---------------------------------------------------------
# Compilación
GSenku.o: GSenku.cpp GSenku.hpp
	${CC} ${CPPFLAGS} -I ../TrabajoMamalonFtRumano_Prime -c GSenku.cpp

mainGSenku.o: mainGSenku.cpp GSenku.hpp
	${CC} ${CPPFLAGS} -I ../TrabajoMamalonFtRumano_Prime -c mainGSenku.cpp

#---------------------------------------------------------
# Linkado
mainGSenku: mainGSenku.o GSenku.o
	${CC} ${CPPFLAGS} -o mainGSenku mainGSenku.o GSenku.o

#---------------------------------------------------------
# Limpieza
clean:
	${RM} mainGSenku.o  mainGSenku
